(function(){
    const state={page:1,pages:1,isUsed:''}
    const view=document.createElement('section');view.className='admin-operation-view';view.innerHTML='<header class="operation-heading"><div><p>超级管理员</p><h1>注册码管理</h1></div><button class="create-code" type="button">新增注册码</button></header><form class="operation-filters"><label>使用状态<select name="isUsed"><option value="">全部</option><option value="false">未使用</option><option value="true">已使用</option></select></label><button type="submit">查询</button></form><div class="operation-result"></div><nav class="operation-pagination"><button class="previous" type="button">上一页</button><span></span><button class="next" type="button">下一页</button></nav>'
    document.body.appendChild(view);AdminViewManager.register(view)
    document.getElementById('registration-codes-button').addEventListener('click',()=>{AdminViewManager.show(view);load()});view.querySelector('form').addEventListener('submit',e=>{e.preventDefault();state.page=1;state.isUsed=e.currentTarget.elements.isUsed.value;load()});view.querySelector('.create-code').addEventListener('click',()=>openEditor());view.querySelector('.previous').addEventListener('click',()=>change(state.page-1));view.querySelector('.next').addEventListener('click',()=>change(state.page+1))
    function change(page){if(page>=1&&page<=state.pages){state.page=page;load()}}
    async function load(){const data=await adminBusinessRequest('/admin/registration-codes/page',{query:{page:state.page,size:20,isUsed:state.isUsed}});if(!data){view.querySelector('.operation-result').innerHTML='<p class="operation-message">无权访问或加载失败</p>';return}render(data)}
    function render(data){const result=view.querySelector('.operation-result');if(!data.items.length)result.innerHTML='<p class="operation-message">暂无注册码</p>';else{const table=document.createElement('table');table.className='operation-table';table.innerHTML='<thead><tr><th>注册码</th><th>状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody></tbody>';data.items.forEach(item=>{const row=document.createElement('tr');row.innerHTML='<td></td><td></td><td></td><td class="table-actions"></td>';row.children[0].textContent=item.code;row.children[1].textContent=item.isUsed?'已使用':'未使用';row.children[2].textContent=item.createTime;const edit=document.createElement('button');edit.textContent='编辑';edit.addEventListener('click',()=>openEditor(item));const del=document.createElement('button');del.textContent='删除';del.className='danger';del.addEventListener('click',()=>remove(item));row.children[3].append(edit,del);table.tBodies[0].appendChild(row)});result.replaceChildren(table)}state.page=data.page;state.pages=Math.max(1,data.pages||1);view.querySelector('.operation-pagination span').textContent=`第 ${state.page} / ${state.pages} 页，共 ${data.total} 条`}
    function openEditor(item=null){const dialog=document.createElement('dialog');dialog.className='operation-dialog operation-small-dialog';dialog.innerHTML='<header><div><p>注册码</p><h2></h2></div><button type="button">×</button></header><form><label>注册码<input name="code" maxlength="128" required></label><label class="used-field"><input name="isUsed" type="checkbox"> 标记为已使用</label><button type="submit">保存</button></form>';dialog.querySelector('h2').textContent=item?'编辑注册码':'新增注册码';dialog.querySelector('[name=code]').value=item?.code||'';dialog.querySelector('[name=isUsed]').checked=Boolean(item?.isUsed);if(!item)dialog.querySelector('.used-field').hidden=true;dialog.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();const body=item?{code:e.currentTarget.elements.code.value.trim(),isUsed:e.currentTarget.elements.isUsed.checked}:{code:e.currentTarget.elements.code.value.trim()};const ok=await adminBusinessRequest(item?`/admin/registration-codes/${item.id}`:'/admin/registration-codes/',{method:item?'PUT':'POST',body});if(ok){Toast.success('注册码已保存');dialog.close();load()}});document.body.appendChild(dialog);dialog.querySelector('header button').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>dialog.remove());dialog.showModal()}
    async function remove(item){if(!confirm(`确认删除注册码 ${item.code} 吗？`))return;const ok=await adminBusinessRequest(`/admin/registration-codes/${item.id}`,{method:'DELETE'});if(ok){Toast.success('注册码已删除');load()}}
})()
